# Generated by Django 6.0.3 on 2026-03-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_oc', models.AutoField(primary_key=True, serialize=False)),
                ('nro_oc', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número OC')),
                ('seccion_solicita', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sección que solicita')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de Solicitud')),
                ('destino', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destino')),
                ('observaciones', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(default='Pendiente', max_length=50, verbose_name='Estado')),
                ('registrado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registrado por')),
                ('archivo_orden', models.FileField(blank=True, null=True, upload_to='compras/ordenes/', verbose_name='Archivo de Orden')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('quien_entrego', models.CharField(blank=True, max_length=200, null=True, verbose_name='Quién entregó')),
                ('observacion_entrega', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observación de entrega')),
                ('origen_fondos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Origen de fondos')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_solicitud', '-id_oc'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ítem')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('cantidad_pedida', models.PositiveIntegerField(verbose_name='Cantidad Pedida')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, verbose_name='Cantidad Recibida')),
                ('fecha_recepcion', models.DateField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('recibido_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Recibido por')),
                ('traido_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Traído por')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(default='Pendiente', max_length=50, verbose_name='Estado')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra')),
            ],
            options={
                'verbose_name': 'Detalle de OC',
                'verbose_name_plural': 'Detalles de OC',
                'ordering': ['orden_compra', 'item'],
            },
        ),
    ]
