# Generated by Django 6.0.3 on 2026-03-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleordencompra',
            options={'ordering': ['orden_compra', 'item'], 'verbose_name': 'Detalle de OC (Seguimiento)', 'verbose_name_plural': 'Seguimiento OC'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-fecha_solicitud', '-id_oc'], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Nueva Orden de Compra'},
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='cantidad_pedida',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Detalle'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='archivo_orden',
            field=models.FileField(blank=True, null=True, upload_to='compras/ordenes/', verbose_name='Foto de la orden'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='destino',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Destino del pedido'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_solicitud',
            field=models.DateField(verbose_name='Fecha solicitud'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='nro_oc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro de orden'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='origen_fondos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Origen del fondo'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='registrado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitado por'),
        ),
    ]
