# Generated by Django 6.0.3 on 2026-03-20 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_detalleordencompra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(default='En curso', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_solicitud',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha solicitud'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='observacion_entrega',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observacion Entrega'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='quien_entrego',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Entrega realizada por'),
        ),
    ]
