# Generated by Django 6.0.3 on 2026-03-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_ordencompra_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('En curso', 'En curso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='En curso', max_length=50, verbose_name='Estado'),
        ),
    ]
