# Generated by Django 6.0.3 on 2026-03-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_ordencompra_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoOC',
            fields=[
            ],
            options={
                'verbose_name': 'Seguimiento OC',
                'verbose_name_plural': 'Seguimiento OC',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('compras.ordencompra',),
        ),
        migrations.AlterModelOptions(
            name='detalleordencompra',
            options={'ordering': ['orden_compra', 'item'], 'verbose_name': 'Detalle de OC', 'verbose_name_plural': 'Detalles de OC'},
        ),
    ]
