# Generated by Django 6.0.3 on 2026-03-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_seguimientooc_alter_detalleordencompra_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordencompra',
            name='estado',
            field=models.CharField(choices=[('En curso', 'En curso'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='En curso', max_length=50, verbose_name='Estado'),
        ),
    ]
