# Generated by Django 6.0.3 on 2026-03-22 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigrama', '0001_initial'),
        ('reclamos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField()),
                ('es_empleado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='reclamos.reclamo')),
            ],
            options={
                'verbose_name': 'Mensaje de Reclamo',
                'verbose_name_plural': 'Mensajes de Reclamo',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='PaseReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pase', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Motivo del pase')),
                ('area_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.area')),
                ('oficina_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.oficina')),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pases', to='reclamos.reclamo')),
                ('usuario_emisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pase de Reclamo',
                'verbose_name_plural': 'Pases de Reclamo',
                'ordering': ['-fecha_pase'],
            },
        ),
    ]
