# Generated by Django 6.0.3 on 2026-03-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0002_mensajereclamo_pasereclamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajereclamo',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
    ]
