# Generated by Django 6.0.3 on 2026-03-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclamos', '0003_mensajereclamo_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasereclamo',
            name='leido_por_vecino',
            field=models.BooleanField(default=False, verbose_name='Leído por el vecino'),
        ),
    ]
