# Generated by Django 6.0.3 on 2026-03-24 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_notificacion'),
        ('reclamos', '0004_pasereclamo_leido_por_vecino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamo',
            name='area',
            field=models.CharField(choices=[('Inspección', 'Inspección'), ('Mantenimiento', 'Mantenimiento'), ('Salud', 'Salud')], max_length=50, verbose_name='Área Municipal'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='barrio',
            field=models.CharField(choices=[('Alberdi', 'Alberdi'), ('Barracas', 'Barracas'), ('Centro', 'Centro'), ('Granaderos a Caballo', 'Granaderos a Caballo'), ('Nueva Roma', 'Nueva Roma'), ('Parque', 'Parque'), ('San Carlos', 'San Carlos'), ('San Jorge', 'San Jorge'), ('Yapeyú', 'Yapeyú'), ('Otro', 'Otro')], max_length=100, verbose_name='Barrio del reclamo'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En Progreso'), ('Resuelto', 'Resuelto'), ('Cerrado', 'Cerrado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='tipo_reclamo',
            field=models.CharField(choices=[('Irregularidades en obras', 'Irregularidades en obras'), ('Actividad comercial irregular', 'Actividad comercial irregular'), ('Poda no autorizada', 'Poda no autorizada'), ('Sustancias peligrosas', 'Sustancias peligrosas'), ('Ocupación de espacios públicos', 'Ocupación de espacios públicos'), ('Aguas servidas', 'Aguas servidas'), ('Micro basural', 'Micro basural'), ('Accesibilidad para personas con discapacidad', 'Accesibilidad para personas con discapacidad'), ('Arreglo calle de ripio', 'Arreglo calle de ripio'), ('Boca de tormenta obstruída', 'Boca de tormenta obstruída'), ('Apertura y limpieza de cuneta', 'Apertura y limpieza de cuneta'), ('Caminos rurales', 'Caminos rurales'), ('Colocación o reposición de tubos media caña cuneta', 'Colocación o reposición de tubos media caña cuneta'), ('Daños en espacios públicos', 'Daños en espacios públicos'), ('Arreglo calle de tierra', 'Arreglo calle de tierra'), ('Colocación de brea', 'Colocación de brea'), ('Plagas y vectores en espacios públicos', 'Plagas y vectores en espacios públicos'), ('Plagas y vectores en propiedad privada', 'Plagas y vectores en propiedad privada')], max_length=100, verbose_name='Tipo de Incidente'),
        ),
        migrations.AlterField(
            model_name='reclamo',
            name='vecino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamos', to='portal.vecino', verbose_name='Vecino'),
        ),
    ]
