# Generated by Django 6.0.3 on 2026-03-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organigrama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadRRHH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_general', models.BooleanField(default=True, verbose_name='¿Es para todos?')),
                ('funcionario_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.funcionario', verbose_name='Empleado Específico')),
            ],
            options={
                'verbose_name': 'Novedad de RRHH',
                'verbose_name_plural': 'Novedades de RRHH',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ReciboSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='recibos/%Y/%m/', verbose_name='Archivo PDF')),
                ('mes', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Mes')),
                ('anio', models.IntegerField(default=2026, verbose_name='Año')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='organigrama.funcionario', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Recibo de Sueldo',
                'verbose_name_plural': 'Recibos de Sueldo',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_correspondiente', models.IntegerField(default=2025, verbose_name='Año Correspondiente')),
                ('dias_totales', models.IntegerField(default=14, verbose_name='Días Totales')),
                ('dias_tomados', models.IntegerField(default=0, verbose_name='Días Tomados')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='organigrama.funcionario', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Vacaciones',
                'verbose_name_plural': 'Control de Vacaciones',
            },
        ),
    ]
