# Generated by Django 6.0.3 on 2026-03-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigrama', '0002_funcionario_celular_funcionario_cuil_and_more'),
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Categoría')),
                ('sueldo_basico', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sueldo Básico')),
            ],
            options={
                'verbose_name': 'Categoría Salarial',
                'verbose_name_plural': 'Categorías Salariales',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa / Organismo')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo / Función')),
                ('fecha_desde', models.DateField(verbose_name='Desde')),
                ('fecha_hasta', models.DateField(blank=True, null=True, verbose_name='Hasta')),
                ('tareas', models.TextField(blank=True, null=True, verbose_name='Tareas Realizadas')),
                ('es_trabajo_actual', models.BooleanField(default=False, verbose_name='Es Trabajo Actual')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia', to='organigrama.funcionario', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Historia Laboral Previa',
            },
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('parentesco', models.CharField(choices=[('CONYUGE', 'Cónyuge'), ('HIJO', 'Hijo/a'), ('PADRE', 'Padre'), ('MADRE', 'Madre'), ('OTRO', 'Otro')], max_length=20, verbose_name='Parentesco')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('discapacidad', models.BooleanField(default=False, verbose_name='Posee Discapacidad')),
                ('escolaridad', models.BooleanField(default=False, verbose_name='En Escolaridad')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='organigrama.funcionario', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Datos Familiares',
            },
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('PRIMARIO', 'Primario'), ('SECUNDARIO', 'Secundario'), ('TERCIARIO', 'Terciario'), ('UNIVERSITARIO', 'Universitario'), ('POSGRADO', 'Posgrado'), ('CURSO', 'Curso/Certificación')], max_length=20, verbose_name='Nivel Educativo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título / Nombre del Curso')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución')),
                ('estado', models.CharField(choices=[('COMPLETO', 'Completo'), ('EN_CURSO', 'En Curso'), ('INCOMPLETO', 'Incompleto')], max_length=20, verbose_name='Estado')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacion', to='organigrama.funcionario', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Formación Académica',
                'verbose_name_plural': 'Estudios y Cursos',
            },
        ),
        migrations.CreateModel(
            name='InformacionSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_basico_personalizado', models.DecimalField(blank=True, decimal_places=2, help_text='Si se deja vacío, se tomará el de la categoría.', max_digits=12, null=True)),
                ('adicional_antiguedad_porcentaje', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='% Antigüedad por Año')),
                ('adicional_titulo_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='% Adicional por Título')),
                ('suplemento_presentismo', models.BooleanField(default=True, verbose_name='Cobra Presentismo')),
                ('otros_adicionales_fijos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Otros Adicionales (Suma Fija)')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos_humanos.categoriasalarial', verbose_name='Categoría')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_salarial', to='organigrama.funcionario', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Información Salarial',
                'verbose_name_plural': 'Información Salarial de Empleados',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Mes')),
                ('anio', models.IntegerField(default=2026, verbose_name='Año')),
                ('sueldo_bruto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sueldo Bruto')),
                ('total_descuentos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Descuentos')),
                ('sueldo_neto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sueldo Neto')),
                ('detalles_json', models.JSONField(blank=True, help_text='Desglose detallado de la liquidación.', null=True)),
                ('fecha_proceso', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='organigrama.funcionario', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Liquidación Mensual',
                'verbose_name_plural': 'Historial de Liquidaciones',
                'unique_together': {('funcionario', 'mes', 'anio')},
            },
        ),
    ]
