# Generated by Django 6.0.3 on 2026-03-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organigrama', '0002_funcionario_celular_funcionario_cuil_and_more'),
        ('recursos_humanos', '0002_categoriasalarial_experiencialaboral_familiar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados (Legajos)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organigrama.funcionario',),
        ),
    ]
