# Generated by Django 6.0.3 on 2026-03-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0003_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionsalarial',
            name='adicional_titulo_porcentaje',
        ),
        migrations.AddField(
            model_name='informacionsalarial',
            name='adicional_titulo_tipo',
            field=models.CharField(choices=[('0', 'Ninguno (0%)'), ('10', 'Secundario (10%)'), ('15', 'Terciario 3 años (15%)'), ('20', 'Univ. 4 años (20%)'), ('25', 'Univ. 5+ años o Posgrado (25%)'), ('17.5', 'Técnico o Pre-univ. (17.5%)')], default='0', max_length=10, verbose_name='Adicional por Título'),
        ),
        migrations.AddField(
            model_name='informacionsalarial',
            name='suplemento_tipo',
            field=models.CharField(choices=[('0', 'Ninguno (0%)'), ('20', 'Riesgo y Peligrosidad (20%)'), ('40', 'Dedicación Exclusiva (40%)'), ('15', 'Tareas Especiales/Asistenciales (15%)'), ('25', 'Responsabilidad Jerárquica (25%)'), ('50', 'Mayor Jornada Laboral (50%)')], default='0', max_length=10, verbose_name='Suplemento Especial'),
        ),
    ]
