services:
  - type: web
    name: sistema-casilda
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd sistema_casilda && gunicorn core.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "True"  # Dejamos en True para la demo inicial si hay errores
      - key: PYTHON_VERSION
        value: "3.11.1"
      - key: RENDER_EXTERNAL_HOSTNAME
        fromContext: hostname
