# Generated by Django 6.0.3 on 2026-03-21 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'REGIO_AREAS',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('area', models.ForeignKey(db_column='ID_AREA', on_delete=django.db.models.deletion.CASCADE, to='organigrama.area')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'REGIO_DIRECCIONES',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('area', models.ForeignKey(blank=True, db_column='ID_AREA', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.area')),
                ('direccion', models.ForeignKey(blank=True, db_column='ID_DIRECCION', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.direccion')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'REGIO_DEPARTAMENTOS',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id_division', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('departamento', models.ForeignKey(db_column='ID_DEPARTAMENTO', on_delete=django.db.models.deletion.CASCADE, to='organigrama.departamento')),
            ],
            options={
                'verbose_name': 'División',
                'verbose_name_plural': 'Divisiones',
                'db_table': 'REGIO_DIVISIONES',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id_oficina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('area', models.ForeignKey(blank=True, db_column='ID_AREA', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.area')),
                ('direccion', models.ForeignKey(blank=True, db_column='ID_DIRECCION', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.direccion')),
                ('division', models.ForeignKey(blank=True, db_column='ID_DIVISION', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.division')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'db_table': 'REGIO_OFICINAS',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id_subdivision', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('area', models.ForeignKey(blank=True, db_column='ID_AREA', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.area')),
                ('departamento', models.ForeignKey(blank=True, db_column='ID_DEPARTAMENTO', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.departamento')),
                ('division', models.ForeignKey(blank=True, db_column='ID_DIVISION', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.division')),
            ],
            options={
                'verbose_name': 'Subdivisión',
                'verbose_name_plural': 'Subdivisiones',
                'db_table': 'REGIO_SUBDIVISIONES',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('departamento', models.ForeignKey(blank=True, db_column='ID_DEPARTAMENTO', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.departamento')),
                ('division', models.ForeignKey(blank=True, db_column='ID_DIVISION', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.division')),
                ('subdivision', models.ForeignKey(blank=True, db_column='ID_SUBDIVISION', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.subdivision')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'REGIO_SECCIONES',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(db_column='ID_FUNCIONARIO', primary_key=True, serialize=False)),
                ('id_empleado_externo', models.IntegerField(blank=True, db_column='ID_EMPLEADO_EXTERNO', null=True, unique=True)),
                ('usuario_login', models.CharField(db_column='USUARIO_LOGIN', max_length=100, unique=True)),
                ('pass_salt', models.CharField(blank=True, db_column='PASS_SALT', max_length=64, null=True)),
                ('pass_hash', models.CharField(blank=True, db_column='PASS_HASH', max_length=64, null=True)),
                ('activo', models.CharField(db_column='ACTIVO', default='S', max_length=1)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, db_column='FECHA_ALTA')),
                ('nombre', models.CharField(blank=True, db_column='NOMBRE', max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, db_column='APELLIDO', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, db_column='EMAIL', max_length=200, null=True)),
                ('rango', models.CharField(choices=[('JEFE', 'Jefe'), ('SECRETARIO', 'Secretario'), ('ADMINISTRATIVO', 'Administrativo'), ('INSPECTOR', 'Inspector'), ('OPERARIO', 'Operario')], default='ADMINISTRATIVO', max_length=50)),
                ('area', models.ForeignKey(blank=True, db_column='ID_AREA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.area')),
                ('departamento', models.ForeignKey(blank=True, db_column='ID_DEPARTAMENTO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.departamento')),
                ('direccion', models.ForeignKey(blank=True, db_column='ID_DIRECCION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.direccion')),
                ('division', models.ForeignKey(blank=True, db_column='ID_DIVISION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.division')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_link', to=settings.AUTH_USER_MODEL)),
                ('oficina', models.ForeignKey(blank=True, db_column='ID_OFICINA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.oficina')),
                ('seccion', models.ForeignKey(blank=True, db_column='ID_SECCION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.seccion')),
                ('subdivision', models.ForeignKey(blank=True, db_column='ID_SUBDIVISION', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.subdivision')),
            ],
            options={
                'verbose_name': 'Funcionario / Empleado',
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'REGIO_FUNCIONARIOS',
            },
        ),
    ]
