# Generated by Django 6.0.3 on 2026-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigrama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='celular',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cuil',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CUIL'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='direccion_domicilio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Domicilio'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('CONVIVIENTE', 'Conviviente')], default='SOLTERO', max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Nombre'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono Fijo'),
        ),
    ]
