# Generated by Django 6.0.3 on 2026-03-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigrama', '0002_funcionario_celular_funcionario_cuil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='nro_legajo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de Legajo'),
        ),
    ]
