# Generated by Django 6.0.3 on 2026-03-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigrama', '0003_funcionario_nro_legajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='direccion_domicilio',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='altura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Calle'),
        ),
    ]
