# Generated by Django 6.0.3 on 2026-03-27 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigrama', '0004_remove_funcionario_direccion_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='departamento',
            field=models.ForeignKey(blank=True, db_column='ID_DEPARTAMENTO', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.departamento'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='seccion',
            field=models.ForeignKey(blank=True, db_column='ID_SECCION', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.seccion'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='subdivision',
            field=models.ForeignKey(blank=True, db_column='ID_SUBDIVISION', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.subdivision'),
        ),
    ]
