# Generated by Django 6.0.3 on 2026-03-27 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigrama', '0005_oficina_departamento_oficina_seccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='area',
            field=models.ForeignKey(blank=True, db_column='ID_AREA', null=True, on_delete=django.db.models.deletion.CASCADE, to='organigrama.area'),
        ),
    ]
