# Generated by Django 6.0.3 on 2026-03-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_turno', models.CharField(choices=[('PSICOFISICO', 'Psicofísico'), ('LICENCIA', 'Licencia de Conducir')], max_length=20, unique=True)),
                ('hora_inicio', models.TimeField(default='07:00')),
                ('hora_fin', models.TimeField(default='13:00')),
                ('turnos_por_hora', models.IntegerField(default=4, help_text='Ej: 4 significa un turno cada 15 minutos exactos.')),
            ],
            options={
                'verbose_name': 'Configuración de Turnos',
                'verbose_name_plural': 'Configuraciones de Turnos',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_turno', models.CharField(choices=[('PSICOFISICO', 'Psicofísico'), ('LICENCIA', 'Licencia de Conducir')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('tipo_licencia', models.CharField(blank=True, help_text='Ej: A, B1, B2, C, etc.', max_length=20, null=True)),
                ('vencimiento_licencia', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento de Licencia Actual')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='portal.vecino')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha', 'hora'],
                'unique_together': {('tipo_turno', 'fecha', 'hora')},
            },
        ),
    ]
