# Generated by Django 6.0.3 on 2026-03-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionturno',
            name='dias_habiles',
            field=models.CharField(default='0,1,2,3,4', help_text='0=Lunes, 4=Viernes. Separado por comas.', max_length=50),
        ),
    ]
