# Generated by Django 6.0.3 on 2026-03-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id_expediente', models.AutoField(primary_key=True, serialize=False)),
                ('nro_expediente', models.CharField(max_length=50, unique=True, verbose_name='Número de Expediente')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('procedencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Procedencia')),
                ('asunto', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Asunto')),
                ('destino', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destino')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('estado', models.CharField(default='En trámite', max_length=50, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observaciones')),
                ('registrado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registrado por')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='expedientes/fotos/', verbose_name='Foto del Expediente')),
                ('tipo_expediente', models.CharField(default='RECIBIDO', max_length=20, verbose_name='Tipo de Expediente')),
                ('origen_interno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Origen Interno')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-fecha_ingreso', '-id_expediente'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoExpediente',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('procedencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Procedencia')),
                ('destino', models.CharField(blank=True, max_length=200, null=True, verbose_name='Destino')),
                ('estado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('observacion', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Observación')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='expedientes/movimientos/', verbose_name='Foto del Movimiento')),
                ('usuario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario')),
                ('fecha_archivado', models.DateField(blank=True, null=True, verbose_name='Fecha de Archivado')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='expedientes.expediente')),
            ],
            options={
                'verbose_name': 'Movimiento de Expediente',
                'verbose_name_plural': 'Movimientos de Expediente',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
