# Generated by Django 6.0.3 on 2026-03-20 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='vecino_titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes', to='portal.vecino', verbose_name='Vecino Titular'),
        ),
    ]
