# Generated by Django 6.0.3 on 2026-03-23 03:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_expediente_vecino_titular'),
        ('organigrama', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoexpediente',
            options={'ordering': ['-fecha_pase'], 'verbose_name': 'Pase de Expediente', 'verbose_name_plural': 'Historial de Pases'},
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='origen_interno',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='procedencia',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='tipo_expediente',
        ),
        migrations.RemoveField(
            model_name='movimientoexpediente',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='movimientoexpediente',
            name='fecha_archivado',
        ),
        migrations.RemoveField(
            model_name='movimientoexpediente',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='movimientoexpediente',
            name='fecha_salida',
        ),
        migrations.RemoveField(
            model_name='movimientoexpediente',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='movimientoexpediente',
            name='procedencia',
        ),
        migrations.RemoveField(
            model_name='movimientoexpediente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='expediente',
            name='actual_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_actuales', to='organigrama.area'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='actual_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_actuales', to='organigrama.departamento'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='actual_direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_actuales', to='organigrama.direccion'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='actual_oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_actuales', to='organigrama.oficina'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='origen_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_creados', to='organigrama.area'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='origen_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_creados', to='organigrama.departamento'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='origen_direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_creados', to='organigrama.direccion'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='origen_oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_creados', to='organigrama.oficina'),
        ),
        migrations.AddField(
            model_name='movimientoexpediente',
            name='destino_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.area'),
        ),
        migrations.AddField(
            model_name='movimientoexpediente',
            name='destino_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.departamento'),
        ),
        migrations.AddField(
            model_name='movimientoexpediente',
            name='destino_direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.direccion'),
        ),
        migrations.AddField(
            model_name='movimientoexpediente',
            name='destino_oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.oficina'),
        ),
        migrations.AddField(
            model_name='movimientoexpediente',
            name='fecha_pase',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha del Pase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientoexpediente',
            name='usuario_emisor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enviado por'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='expedientes/fotos/', verbose_name='Documento/Foto'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='registrado_por',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registrado por (Mesa Entrada)'),
        ),
        migrations.AlterField(
            model_name='movimientoexpediente',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nuevo Estado'),
        ),
        migrations.AlterField(
            model_name='movimientoexpediente',
            name='observacion',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Nota de Pase'),
        ),
    ]
