# Generated by Django 6.0.3 on 2026-03-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_alter_movimientoexpediente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='nro_expediente',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Expediente'),
        ),
    ]
