# Generated by Django 6.0.3 on 2026-03-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_alter_expediente_nro_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='apellido_titular_manual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Titular (Manual)'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='dni_titular_manual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI Titular (Manual)'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='nombre_titular_manual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Titular (Manual)'),
        ),
    ]
