# Generated by Django 6.0.3 on 2026-03-30 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_expediente_apellido_titular_manual_and_more'),
        ('organigrama', '0006_seccion_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='confirmado',
            field=models.BooleanField(default=False, verbose_name='Confirmado por Mesa'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_creados_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expediente',
            name='solicitante_interno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_solicitados', to='organigrama.funcionario'),
        ),
    ]
