# Generated by Django 6.0.3 on 2026-03-30 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_expediente_confirmado_expediente_creado_por_and_more'),
        ('organigrama', '0006_seccion_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='dirigido_a',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirigido a (Nombre/Cargo)'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='oficina_destino_sugerida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_sugeridos_destino', to='organigrama.oficina'),
        ),
    ]
