# Generated by Django 6.0.3 on 2026-04-01 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0007_expediente_dirigido_a_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='ultima_resolucion',
            field=models.TextField(blank=True, null=True, verbose_name='Última Resolución/Nota'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='Visto por Destino Actual'),
        ),
        migrations.AddField(
            model_name='movimientoexpediente',
            name='resolucion',
            field=models.TextField(blank=True, null=True, verbose_name='Resolución en esta instancia'),
        ),
        migrations.CreateModel(
            name='NotificacionExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expedientes.expediente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_expedientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de Expediente',
                'verbose_name_plural': 'Notificaciones de Expedientes',
                'ordering': ['-fecha'],
            },
        ),
    ]
