# Generated by Django 6.0.3 on 2026-04-01 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0008_expediente_ultima_resolucion_expediente_visto_and_more'),
        ('organigrama', '0006_seccion_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='oficina_destino_sugerida',
        ),
        migrations.AddField(
            model_name='expediente',
            name='actual_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_actuales', to='organigrama.division'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='actual_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_actuales', to='organigrama.seccion'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='actual_subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_actuales', to='organigrama.subdivision'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='destino_area_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugeridos_area', to='organigrama.area'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='destino_departamento_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugeridos_depto', to='organigrama.departamento'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='destino_direccion_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugeridos_direccion', to='organigrama.direccion'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='destino_division_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugeridos_division', to='organigrama.division'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='destino_oficina_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugeridos_oficina', to='organigrama.oficina'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='destino_seccion_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugeridos_seccion', to='organigrama.seccion'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='destino_subdivision_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugeridos_subdivision', to='organigrama.subdivision'),
        ),
        migrations.AddField(
            model_name='movimientoexpediente',
            name='destino_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.division'),
        ),
        migrations.AddField(
            model_name='movimientoexpediente',
            name='destino_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.seccion'),
        ),
        migrations.AddField(
            model_name='movimientoexpediente',
            name='destino_subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.subdivision'),
        ),
    ]
