# Generated by Django 6.0.3 on 2026-04-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0009_remove_expediente_oficina_destino_sugerida_and_more'),
        ('organigrama', '0006_seccion_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='origen_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_creados', to='organigrama.division'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='origen_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_creados', to='organigrama.seccion'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='origen_subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_creados', to='organigrama.subdivision'),
        ),
    ]
