# Generated by Django 6.0.3 on 2026-03-21 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('raza', models.CharField(blank=True, max_length=50, null=True)),
                ('especie', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'db_table': 'ANIMALES',
            },
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('nomenclatura', models.CharField(max_length=50, unique=True)),
                ('cuil', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('manzana', models.CharField(blank=True, max_length=10, null=True)),
                ('seccion', models.CharField(blank=True, max_length=10, null=True)),
                ('parcela', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_inmueble', models.CharField(blank=True, max_length=50, null=True)),
                ('uso_inmueble', models.CharField(blank=True, max_length=50, null=True)),
                ('metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'db_table': 'INMUEBLES',
            },
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id_inspector', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Inspector',
                'verbose_name_plural': 'Inspectores',
                'db_table': 'INSPECTORES',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_acta', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Motivo de Infracción',
                'verbose_name_plural': 'Motivos de Infracción',
                'db_table': 'MOTIVOS',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'PERSONAS',
            },
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id_acta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_acta', models.CharField(max_length=50)),
                ('fecha_infraccion', models.DateField(default=django.utils.timezone.now)),
                ('lugar_infraccion', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('uf', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidades Fijas (UF)')),
                ('foto_infraccion', models.ImageField(blank=True, null=True, upload_to='multas/fotos/')),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('numero_acta', models.IntegerField(blank=True, null=True)),
                ('animal', models.ForeignKey(blank=True, db_column='ID_ANIMAL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas', to='multas.animal')),
                ('inmueble', models.ForeignKey(blank=True, db_column='ID_INMUEBLE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas', to='multas.inmueble')),
                ('inspector', models.ForeignKey(blank=True, db_column='ID_INSPECTOR', null=True, on_delete=django.db.models.deletion.SET_NULL, to='multas.inspector')),
                ('motivo', models.ForeignKey(blank=True, db_column='ID_MOTIVO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='multas.motivo')),
                ('persona', models.ForeignKey(blank=True, db_column='ID_PERSONA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas', to='multas.persona')),
            ],
            options={
                'verbose_name': 'Acta de Infracción',
                'verbose_name_plural': 'Actas de Infracción',
                'db_table': 'ACTAS',
            },
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id_doc', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_doc', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_generacion', models.DateField(default=django.utils.timezone.now)),
                ('usuario_genera', models.CharField(blank=True, max_length=50, null=True)),
                ('acta', models.ForeignKey(blank=True, db_column='ID_ACTA', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='multas.acta')),
            ],
            options={
                'verbose_name': 'Documentación',
                'verbose_name_plural': 'Documentaciones',
                'db_table': 'DOCUMENTACION',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='propietario',
            field=models.ForeignKey(blank=True, db_column='ID_PROPIETARIO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='multas.persona'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('anio_fabricacion', models.IntegerField(blank=True, null=True, verbose_name='Año Fabricación')),
                ('titular', models.ForeignKey(blank=True, db_column='ID_TITULAR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='multas.persona')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'VEHICULOS',
            },
        ),
        migrations.AddField(
            model_name='acta',
            name='vehiculo',
            field=models.ForeignKey(blank=True, db_column='ID_VEHICULO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actas', to='multas.vehiculo'),
        ),
    ]
