# Generated by Django 6.0.3 on 2026-03-21 19:02

from django.db import migrations

def load_data(apps, schema_editor):
    Motivo = apps.get_model('multas', 'Motivo')

    motivos = [
        (24, 'VEHICULO', 'Licencia de conducir adulterada'),
        (7, 'VEHICULO', 'Circular con chapas patentes adulteradas'),
        (28, 'VEHICULO', 'Circular sin dispositivos de seguridad'),
        (30, 'VEHICULO', 'Circular en contramano/girar'),
        (11, 'VEHICULO', 'Circular con transporte en zona prohibida (Ord. 2847/17)'),
        (41, 'VEHICULO', 'Por efectuar picadas'),
        (60, 'INMUEBLE', 'Otros'),
        (13, 'VEHICULO', 'Por circular sobre veredas'),
        (33, 'VEHICULO', 'Por desobediencia'),
        (35, 'VEHICULO', 'Conducir con imprudencia'),
        (44, 'VEHICULO', 'Conducir en estado de ebriedad (Ord. 2082/12)'),
        (48, 'VEHICULO', 'Estacionar frente a un garage'),
        (36, 'VEHICULO', 'Estacionar en ochava, F/amarilla, E/señales'),
        (50, 'VEHICULO', 'Estacionamiento sobre vereda'),
        (57, 'INMUEBLE', 'Ramas'),
        (23, 'VEHICULO', 'No exhibir seguro obligatorio (Ord. 1231/05)'),
        (6, 'VEHICULO', 'Falta de licencia de conducir'),
        (27, 'VEHICULO', 'Circular sin chapas patentes'),
        (10, 'VEHICULO', 'Circular sin casco conductor/acompañante'),
        (31, 'VEHICULO', 'Por girar en U o no respetar rotondas'),
        (45, 'VEHICULO', 'Conducción de menor (Ord. 380 - inc.b.)'),
        (46, 'VEHICULO', 'Cruzar semáforo en rojo'),
        (47, 'VEHICULO', 'Reparar vehículos en calle/vereda'),
        (37, 'VEHICULO', 'Estacionar en paradas de moto o transporte escolar'),
        (51, 'VEHICULO', 'Estacionamiento en zona prohibida (Ord. 2847/17)'),
        (39, 'VEHICULO', 'Estacionamiento en rampas (Ord. 380)'),
        (40, 'INMUEBLE', 'Tierra'),
        (61, 'INMUEBLE', 'Basura'),
        (58, 'INMUEBLE', 'Aguas servidas'),
        (63, 'INMUEBLE', 'Volquete'),
        (26, 'VEHICULO', 'No exhibir documentación del vehículo'),
        (8, 'VEHICULO', 'Circular con escape prohibido/ruido'),
        (49, 'VEHICULO', 'Estacionamiento sistemático'),
        (52, 'VEHICULO', 'Estacionamiento en parada de taxis/remises'),
        (56, 'INMUEBLE', 'Arena'),
        (59, 'INMUEBLE', 'Cerramiento obras'),
        (25, 'VEHICULO', 'Licencia de conducir vencida'),
        (9, 'VEHICULO', 'Circular sin luces reglamentarias'),
        (29, 'VEHICULO', 'Circular mas de dos personas en moto'),
        (12, 'VEHICULO', 'Por exceso de pasajeros'),
        (32, 'VEHICULO', 'Por girar a la izquiera'),
        (42, 'VEHICULO', 'Por retroceso indebido'),
        (34, 'VEHICULO', 'Uso de celular mientras conduce'),
        (43, 'VEHICULO', 'Conducir en estado inhabilitado'),
        (38, 'VEHICULO', 'Estacionar a la izquierda o en doble fila'),
        (53, 'VEHICULO', 'Moto estacionada en lugar indebido'),
        (54, 'INMUEBLE', 'Escombros'),
        (55, 'INMUEBLE', 'Demalezamiento'),
        (62, 'INMUEBLE', 'Poda de arbol')
    ]

    for m_id, t_acta, desc in motivos:
        Motivo.objects.get_or_create(id_motivo=m_id, defaults={'tipo_acta': t_acta, 'descripcion': desc})

def reverse_load(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data, reverse_load),
    ]
