# Generated by Django 6.0.3 on 2026-03-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0002_preload_motivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='tipo_acta',
            field=models.CharField(choices=[('ANIMAL', 'Animal'), ('VEHICULO', 'Vehículo'), ('INMUEBLE', 'Inmueble')], max_length=50),
        ),
    ]
