# Generated by Django 6.0.3 on 2026-03-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multas', '0003_alter_acta_tipo_acta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada'), ('CADUCA', 'Caduca')], default='PENDIENTE', max_length=20),
        ),
    ]
