import os, django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "core.settings")
django.setup()

from empleo.models import RubroEmpleo, PuestoEmpleo

rubros_data = [
    (2, 'Operario de Planta'),
    (3, 'Tornería / CNC'),
    (5, 'Electricidad Industrial'),
    (25, 'Refrigeración / HVAC'),
    (9, 'Administrativo / Contable'),
    (11, 'Salud'),
    (13, 'Agro / Campo'),
    (21, 'Metalúrgica / Soldadura'),
    (7, 'Electricidad Domiciliaria'),
    (26, 'Atención al Público'),
    (27, 'Ventas / Comercial'),
    (10, 'Logística / Depósito'),
    (14, 'Otros Oficios'),
    (41, 'Servicio Doméstico'),
    (23, 'Mecánica Automotriz'),
    (6, 'Construcción / Albañilería'),
    (24, 'Gasista / Plomería'),
    (29, 'Educación'),
    (12, 'Tecnología / Sistemas'),
    (22, 'Mantenimiento Industrial'),
    (4, 'Carpintería / Herrería'),
    (8, 'Jardinería / Parquización'),
    (28, 'Gastronomía')
]

for r_id, desc in rubros_data:
    RubroEmpleo.objects.get_or_create(id_rubro=r_id, defaults={'descripcion': desc, 'activo': 'S'})

puestos_data = [
    (2, 'Operario de línea', 2),
    (4, 'Herrero', 5), # Wait, the image says '5 | 4 | Herrero'. ID_PUESTO 5, ID_RUBRO 4.
    (5, 'Instrumentista', 24), # Image: 24 | 5 | Instrumentista. ID_PUESTO 24, ID_RUBRO 5. Let's use (rubro_id, descripcion).
]
# Let's map it as (rubro_id, descripcion) and we will just get_or_create by those two!
# This ignores ID_PUESTO to prevent collisions, the DB will assign an ID if it's new.
puestos_raw = [
    (2, 'Operario de línea'),
    (4, 'Herrero'),
    (5, 'Instrumentista'),
    (11, 'Acompañante terapéutico'),
    (13, 'Peón rural'),
    (13, 'Tractorista'),
    (21, 'Soldador'),
    (27, 'Telemarketer'),
    (10, 'Depósito'),
    (14, 'Carga/descarga'),
    (6, 'Albañil'),
    (6, 'Oficial'),
    (6, 'Medio oficial'),
    (24, 'Gasista'),
    (12, 'Programador'),
    (2, 'Operario general'),
    (4, 'Operario de taller'),
    (4, 'Lijador'),
    (8, 'Ayudante de albañil'),
    (6, 'Peón de albañil'),
    (8, 'Riego manual'),
    (10, 'Embalador'),
    (10, 'Repositor'),
    (11, 'Recepción médica'),
    (13, 'Ayudante tambo'),
    (22, 'Engrasador'),
    (22, 'Lubricador'),
    (23, 'Lavadero automotor'),
    (24, 'Ayudante de plomería'),
    (27, 'Cajero'),
    (11, 'Odontólogo/a'),
    (11, 'Asistente Odontológico'),
    (11, 'Psicólogo/a'),
    (11, 'Chofer de ambulancia'),
    (9, 'Administrativo'),
    (11, 'Médico'),
    (26, 'Atención al cliente'),
    (23, 'Mecánico'),
    (24, 'Plomero'),
    (29, 'Auxiliar de educación'),
    (12, 'Soporte técnico'),
    (22, 'Mantenimiento general'),
    (8, 'Jardinero'),
    (2, 'Operario de limpieza industrial'),
    (2, 'Auxiliar de producción'),
    (4, 'Ayudante de carpintería'),
    (4, 'Ayudante de herrería'),
    (5, 'Ayudante electricista industrial'),
    (5, 'Bobinador'),
    (5, 'Cableador'),
    (6, 'Peón de obra'),
    (8, 'Mantenimiento de espacios verdes'),
    (10, 'Peón de depósito'),
    (24, 'Montador'),
    (9, 'Administrativo de sanatorio'),
    (24, 'Ayudante gasista'),
    (27, 'Cajera'),
    (29, 'Ayudante de sala'),
    (11, 'Bioquímico'),
    (11, 'Pediatra'),
    (11, 'Obstetra / Partera'),
    (41, 'Limpieza de consultorio'),
    (3, 'Operador CNC'),
    (5, 'Electricista industrial'),
    (21, 'Plegador'),
    (11, 'Enfermero'),
    (9, 'Asistente contable'),
    (41, 'Niñera'),
    (41, 'Cuidadora'),
    (28, 'Cocinero'),
    (28, 'Lavacopas'),
    (28, 'Camarero'),
    (2, 'Clasificador manual'),
    (21, 'Peón metalúrgico'),
    (4, 'Pintor de estructuras'),
    (10, 'Ayudante de carga'),
    (11, 'Camillero'),
    (4, 'Armador de muebles'),
    (22, 'Peón técnico'),
    (23, 'Auxiliar de alineación'),
    (28, 'Ayudante de cocina'),
    (29, 'Colaborador escolar'),
    (11, 'Farmacéutico/a'),
    (11, 'Técnico de Laboratorio'),
    (11, 'Kinesiólogo/a'),
    (11, 'Fonoaudiólogo/a'),
    (41, 'Cuidado de personas con discapacidad'),
    (2, 'Ayudante de almacén'),
    (5, 'Tornero'),
    (4, 'Carpintero'),
    (25, 'Técnico HVAC'),
    (21, 'Armador'),
    (21, 'Tubo estructural'),
    (2, 'Embalado'),
    (6, 'Ayudante pluvial'),
    (6, 'Ayudante de demolición'),
    (9, 'Data entry'),
    (9, 'Recepcionista administrativo'),
    (11, 'Auxiliar de enfermería'),
    (12, 'Auxiliar de Redes'),
    (14, 'Tapicero'),
    (14, 'Vidriero'),
    (14, 'Techista'),
    (28, 'Repartidor'),
    (27, 'Picador'),
    (11, 'Radiólogo/a'),
    (11, 'Técnico en Radiología'),
    (11, 'Terapeuta Ocupacional'),
    (11, 'Acompañante Terapéutico'),
    (41, 'Tareas generales del hogar'),
    (41, 'Niñera'),
    (41, 'Cocina básica domiciliaria')
]

for r_id, desc in puestos_raw:
    # Attempt to link to rubro
    rubro_obj = RubroEmpleo.objects.filter(id_rubro=r_id).first()
    if rubro_obj:
        PuestoEmpleo.objects.get_or_create(rubro=rubro_obj, descripcion=desc, defaults={'activo': 'S'})

print(f"Loaded {len(rubros_data)} rubros and {len(puestos_raw)} puestos successfully.")
