# Generated by Django 6.0.3 on 2026-03-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitacionFeriante',
            fields=[
                ('id_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción')),
                ('organismo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Organismo')),
                ('estado', models.CharField(default='ACTIVO', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='RubroFeriante',
            fields=[
                ('id_rubro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Rubro')),
                ('estado', models.CharField(default='ACTIVO', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
            },
        ),
        migrations.CreateModel(
            name='Feriante',
            fields=[
                ('id_feriante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('sexo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sexo')),
                ('mail', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('red_social', models.CharField(blank=True, max_length=150, null=True, verbose_name='Red Social')),
                ('nombre_emprendimiento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Emprendimiento')),
                ('tipo_elaboracion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Elaboración')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ferias/feriantes/', verbose_name='Foto del Feriante')),
                ('capacitaciones', models.ManyToManyField(blank=True, to='ferias.capacitacionferiante', verbose_name='Capacitaciones Realizadas')),
                ('rubros', models.ManyToManyField(blank=True, to='ferias.rubroferiante', verbose_name='Rubros')),
            ],
            options={
                'verbose_name': 'Feriante',
                'verbose_name_plural': 'Feriantes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
