# Generated by Django 6.0.3 on 2026-03-20 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubroferiante',
            options={'ordering': ['nombre'], 'verbose_name': 'Rubro', 'verbose_name_plural': 'Rubros'},
        ),
        migrations.AddField(
            model_name='feriante',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feriantes_fk', to='ferias.rubroferiante', verbose_name='Rubro'),
        ),
        migrations.CreateModel(
            name='SubrubroFeriante',
            fields=[
                ('id_subrubro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Subrubro')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrubros', to='ferias.rubroferiante', verbose_name='Rubro')),
            ],
            options={
                'verbose_name': 'Subrubro',
                'verbose_name_plural': 'Subrubros',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='feriante',
            name='subrubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ferias.subrubroferiante', verbose_name='Subrubro'),
        ),
    ]
