# Generated by Django 6.0.3 on 2026-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0002_alter_rubroferiante_options_feriante_rubro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriante',
            name='tipo_elaboracion',
            field=models.CharField(blank=True, choices=[('Artesanal', 'Artesanal'), ('Reventa', 'Reventa'), ('Mixto', 'Mixto')], max_length=50, null=True, verbose_name='Tipo de Elaboración'),
        ),
    ]
