# Generated by Django 6.0.3 on 2026-03-20 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0003_alter_feriante_tipo_elaboracion'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feriante',
            name='vecino_titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_feriante', to='portal.vecino', verbose_name='Vecino Titular'),
        ),
    ]
