# Generated by Django 6.0.3 on 2026-03-21 18:51

from django.db import migrations

def load_data(apps, schema_editor):
    RubroFeriante = apps.get_model('ferias', 'RubroFeriante')
    SubrubroFeriante = apps.get_model('ferias', 'SubrubroFeriante')

    rubros = [
        {'id_rubro': 6, 'nombre': 'Reventa / Varios', 'estado': 'ACTIVO'},
        {'id_rubro': 8, 'nombre': 'Cultura pop y coleccionables', 'estado': 'ACTIVO'},
        {'id_rubro': 2, 'nombre': 'Arte visual', 'estado': 'ACTIVO'},
        {'id_rubro': 3, 'nombre': 'Indumentaria y accesorios', 'estado': 'ACTIVO'},
        {'id_rubro': 4, 'nombre': 'Bienestar', 'estado': 'ACTIVO'},
        {'id_rubro': 1, 'nombre': 'Gastronomía', 'estado': 'ACTIVO'},
        {'id_rubro': 5, 'nombre': 'Decoración y hogar', 'estado': 'ACTIVO'},
        {'id_rubro': 7, 'nombre': 'Institucional / Comunitarios', 'estado': 'ACTIVO'}
    ]

    for r in rubros:
        RubroFeriante.objects.get_or_create(id_rubro=r['id_rubro'], defaults={'nombre': r['nombre'], 'estado': r['estado']})

    subrubros = [
        (23, 1, 'Chocolates'), (32, 3, 'Bijou'), (35, 4, 'Piedras'), (14, 5, 'Madera / Carpintería - Metales / Herrería'),
        (38, 5, 'Papel'), (44, 8, 'Juegos de mesa'), (5, 1, 'Bebidas artesanales'), (25, 1, 'Hierbas naturales'),
        (26, 2, 'Pintura'), (29, 3, 'Ropa artesanal'), (11, 4, 'Aromas textiles'), (33, 4, 'Spray áuricos'),
        (39, 5, 'Duendes, atrapasueños, muñecos, etc'), (16, 5, 'Plantas ornamentales'), (17, 6, 'Mates'), (63, 8, 'Pines'),
        (1, 1, 'Panificados'), (21, 1, 'Dulces artesanales'), (2, 1, 'Alfajores'), (22, 1, 'Mermeladas'),
        (3, 1, 'Pastelería'), (9, 3, 'Bolsos y mochilas'), (10, 3, 'Marroquinería'), (31, 3, 'Accesorios textiles'),
        (13, 4, 'Cosmética natural'), (19, 6, 'Cremas y cosméticos'), (42, 7, 'Proyecto social'), (62, 8, 'Calcomanías e imanes'),
        (64, 8, 'Objetos 3D'), (43, 8, 'Sellos'), (66, 1, 'Huerta orgánica'), (24, 1, 'Salames y quesos artesanales'),
        (8, 2, 'Calcomanías e imanes'), (28, 2, 'Diseño gráfico'), (34, 4, 'Sahumerios'), (37, 5, 'Tejido'),
        (18, 6, 'Perfumes alternativos'), (20, 6, 'Artículos de bazar'), (41, 7, 'Cooperativa'), (4, 1, 'Comidas regionales'),
        (6, 1, 'Artículos libres de gluten'), (7, 2, 'Ilustración'), (27, 2, 'Fotografía'), (30, 3, 'Calzados'),
        (12, 4, 'Velas'), (15, 5, 'Cerámica – Porcelana fría'), (36, 5, 'Vidrio'), (40, 7, 'ONG'),
        (61, 7, 'Institucione educativa'), (65, 8, 'Artículos retro')
    ]

    for s_id, r_id, nombre in subrubros:
        try:
            rubro_obj = RubroFeriante.objects.get(id_rubro=r_id)
            SubrubroFeriante.objects.get_or_create(id_subrubro=s_id, defaults={'rubro': rubro_obj, 'nombre': nombre})
        except RubroFeriante.DoesNotExist:
            pass

def reverse_load(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0004_feriante_vecino_titular'),
    ]

    operations = [
        migrations.RunPython(load_data, reverse_load),
    ]
