# Generated by Django 6.0.3 on 2026-03-23 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0005_preload_rubros_feriantes'),
        ('portal', '0002_localidad_vecino_localidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feriante',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='feriante',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.localidad', verbose_name='Localidad'),
        ),
    ]
