# Generated by Django 6.0.3 on 2026-03-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0006_remove_feriante_ciudad_feriante_localidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feria',
            fields=[
                ('id_feria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Feria')),
                ('fecha', models.DateField(verbose_name='Día')),
                ('horario', models.CharField(max_length=100, verbose_name='Horario')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feria',
                'verbose_name_plural': 'Ferias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionFeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado')], default='SOLICITADO', max_length=20, verbose_name='Estado')),
                ('feria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='ferias.feria', verbose_name='Feria')),
                ('feriante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_feria', to='ferias.feriante', verbose_name='Feriante')),
            ],
            options={
                'verbose_name': 'Inscripción a Feria',
                'verbose_name_plural': 'Inscripciones a Ferias',
                'unique_together': {('feria', 'feriante')},
            },
        ),
    ]
