# Generated by Django 6.0.3 on 2026-03-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0007_feria_inscripcionferia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feriante',
            name='direccion',
        ),
        migrations.AddField(
            model_name='feriante',
            name='altura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='feriante',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Calle'),
        ),
    ]
