# Generated by Django 6.0.3 on 2026-03-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0008_remove_feriante_direccion_feriante_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feriante',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=10, null=True, verbose_name='Sexo'),
        ),
    ]
