# Generated by Django 6.0.3 on 2026-03-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoDisponibilidad',
            fields=[
                ('id_disp', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoIdioma',
            fields=[
                ('id_catalogo_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoLicencia',
            fields=[
                ('id_licencia', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('activo', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoSituacion',
            fields=[
                ('id_situacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(default='Santa Fe', max_length=100)),
                ('activo', models.CharField(default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id_postulante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=30, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad_detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('cp', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.EmailField(blank=True, max_length=150, null=True)),
                ('situacion_actual', models.CharField(blank=True, max_length=50, null=True)),
                ('sobre_mi', models.TextField(blank=True, null=True)),
                ('movilidad_propia', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1)),
                ('medio_movilidad', models.CharField(blank=True, max_length=50, null=True)),
                ('licencia_conducir', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1)),
                ('licencia_categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('licencia_vencimiento', models.DateField(blank=True, null=True)),
                ('disponibilidad_viajar', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1)),
                ('disponibilidad_horaria', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=30)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuestoEmpleo',
            fields=[
                ('id_puesto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('activo', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RubroEmpleo',
            fields=[
                ('id_rubro', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('activo', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id_idioma', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(max_length=100)),
                ('lee', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1)),
                ('habla', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1)),
                ('escribe', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1)),
                ('nivel_idiomas', models.CharField(blank=True, choices=[('BASICO', 'Básico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado'), ('NATIVO', 'Nativo')], max_length=20, null=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='empleo.postulante')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id_experiencia', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('puesto_experiencia', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=300, null=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='empleo.postulante')),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(blank=True, max_length=30, null=True)),
                ('carrera', models.CharField(blank=True, max_length=200, null=True)),
                ('institucion', models.CharField(blank=True, max_length=200, null=True)),
                ('anio', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_estudio', models.CharField(blank=True, max_length=20, null=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='empleo.postulante')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(blank=True, max_length=200, null=True)),
                ('institucion_cursos', models.CharField(blank=True, max_length=200, null=True)),
                ('anio_cursos', models.CharField(blank=True, max_length=10, null=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='empleo/certificados/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='empleo.postulante')),
            ],
        ),
        migrations.AddField(
            model_name='postulante',
            name='puestos',
            field=models.ManyToManyField(blank=True, to='empleo.puestoempleo'),
        ),
        migrations.AddField(
            model_name='puestoempleo',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='empleo.rubroempleo'),
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id_postulacion', models.AutoField(primary_key=True, serialize=False)),
                ('puesto', models.CharField(blank=True, max_length=200, null=True)),
                ('orden', models.PositiveIntegerField(blank=True, null=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='empleo.postulante')),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleo.rubroempleo')),
            ],
        ),
    ]
