# Generated by Django 6.0.3 on 2026-03-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogoDisponibilidad',
        ),
        migrations.AlterModelOptions(
            name='postulante',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Formulario Postulante', 'verbose_name_plural': 'Nuevo Postulante'},
        ),
        migrations.AlterField(
            model_name='postulante',
            name='disponibilidad_horaria',
            field=models.CharField(blank=True, choices=[('2', 'Mañana'), ('21', 'Part Time'), ('23', 'Fin de Semana'), ('1', 'Full Time'), ('22', 'Turnos Rotativos'), ('3', 'Tarde')], max_length=200, null=True),
        ),
    ]
