# Generated by Django 6.0.3 on 2026-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0002_delete_catalogodisponibilidad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogoIdioma',
        ),
        migrations.AlterField(
            model_name='idioma',
            name='idioma',
            field=models.CharField(choices=[('1', 'Español'), ('2', 'Inglés'), ('3', 'Portugués'), ('4', 'Francés'), ('5', 'Alemán'), ('6', 'Chino Mandarín'), ('7', 'Lengua de Señas Argentina'), ('21', 'Italiano'), ('8', 'Otro')], max_length=100),
        ),
    ]
