# Generated by Django 6.0.3 on 2026-03-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0003_delete_catalogoidioma_alter_idioma_idioma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogoLicencia',
        ),
        migrations.AlterField(
            model_name='postulante',
            name='licencia_categoria',
            field=models.CharField(blank=True, choices=[('2', 'A'), ('21', 'B1'), ('3', 'B2'), ('4', 'C'), ('5', 'D'), ('22', 'E'), ('6', 'Profesional')], max_length=50, null=True),
        ),
    ]
