# Generated by Django 6.0.3 on 2026-03-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0004_delete_catalogolicencia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatalogoSituacion',
        ),
        migrations.AlterField(
            model_name='postulante',
            name='situacion_actual',
            field=models.CharField(blank=True, choices=[('1', 'Desocupado'), ('2', 'Estudiante'), ('3', 'Changas/Eventual'), ('4', 'Monotributista'), ('21', 'Empleado')], max_length=50, null=True),
        ),
    ]
