# Generated by Django 6.0.3 on 2026-03-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0005_delete_catalogosituacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Localidad',
        ),
        migrations.AlterField(
            model_name='postulante',
            name='localidad',
            field=models.CharField(blank=True, choices=[('1', 'Casilda'), ('2', 'Arteaga'), ('3', 'Arequito'), ('4', 'Berabevú'), ('5', 'Chañar Ladeado'), ('6', 'Gödeken'), ('7', 'Sanford'), ('21', 'Bigand'), ('22', 'Chabás'), ('23', 'Los Molinos'), ('24', 'Villada'), ('25', 'Fuentes'), ('100', 'Rosario'), ('101', 'Venado Tuerto'), ('102', 'San Lorenzo'), ('103', 'Villa Constitución'), ('104', 'Firmat'), ('105', 'Roldán'), ('106', 'Funes'), ('107', 'Pujato'), ('108', 'Zavalla'), ('109', 'Pérez'), ('8', 'Otro')], max_length=100, null=True),
        ),
    ]
