# Generated by Django 6.0.3 on 2026-03-20 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0006_delete_localidad_alter_postulante_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleo.puestoempleo'),
        ),
    ]
