# Generated by Django 6.0.3 on 2026-03-20 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0007_alter_postulacion_puesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='puesto_experiencia',
        ),
        migrations.AddField(
            model_name='experiencia',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleo.rubroempleo'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='empresa',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
