# Generated by Django 6.0.3 on 2026-03-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0008_remove_experiencia_puesto_experiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleo.puestoempleo'),
        ),
    ]
