# Generated by Django 6.0.3 on 2026-03-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0009_experiencia_puesto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puestoempleo',
            options={'ordering': ['descripcion']},
        ),
        migrations.AlterModelOptions(
            name='rubroempleo',
            options={'ordering': ['descripcion']},
        ),
    ]
