# Generated by Django 6.0.3 on 2026-03-20 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0010_alter_puestoempleo_options_alter_rubroempleo_options'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postulante',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Formulario Postulante', 'verbose_name_plural': 'Postulantes'},
        ),
        migrations.AddField(
            model_name='postulante',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='empleo/cvs/', verbose_name='Curriculum Vitae (PDF)'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='vecino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulaciones_empleo', to='portal.vecino', verbose_name='Vecino Titular'),
        ),
    ]
