# Generated by Django 6.0.3 on 2026-03-21 19:02

from django.db import migrations

def load_data(apps, schema_editor):
    RubroEmpleo = apps.get_model('empleo', 'RubroEmpleo')
    PuestoEmpleo = apps.get_model('empleo', 'PuestoEmpleo')

    rubros = [
        (2, 'Operario de Planta'), (3, 'Tornería / CNC'), (5, 'Electricidad Industrial'),
        (25, 'Refrigeración / HVAC'), (9, 'Administrativo / Contable'), (11, 'Salud'),
        (13, 'Agro / Campo'), (21, 'Metalúrgica / Soldadura'), (7, 'Electricidad Domiciliaria'),
        (26, 'Atención al Público'), (27, 'Ventas / Comercial'), (10, 'Logística / Depósito'),
        (14, 'Otros Oficios'), (41, 'Servicio Doméstico'), (23, 'Mecánica Automotriz'),
        (6, 'Construcción / Albañilería'), (24, 'Gasista / Plomería'), (29, 'Educación'),
        (12, 'Tecnología / Sistemas'), (22, 'Mantenimiento Industrial'), (4, 'Carpintería / Herrería'),
        (8, 'Jardinería / Parquización'), (28, 'Gastronomía')
    ]

    for r_id, desc in rubros:
        RubroEmpleo.objects.get_or_create(id_rubro=r_id, defaults={'descripcion': desc, 'activo': 'S'})

    puestos = [
        (2, 2, 'Operario de línea'), (5, 4, 'Herrero'), (24, 5, 'Instrumentista'), (27, 11, 'Acompañante terapéutico'),
        (12, 13, 'Peón rural'), (13, 13, 'Tractorista'), (28, 21, 'Soldador'), (16, 27, 'Telemarketer'),
        (32, 10, 'Depósito'), (18, 14, 'Carga/descarga'), (20, 6, 'Albañil'), (33, 6, 'Oficial'),
        (41, 6, 'Medio oficial'), (34, 24, 'Gasista'), (45, 12, 'Programador'), (61, 2, 'Operario general'),
        (84, 4, 'Operario de taller'), (85, 4, 'Lijador'), (89, 6, 'Ayudante de albañil'), (92, 8, 'Peón de vivero'),
        (71, 8, 'Riego manual'), (94, 10, 'Embalador'), (74, 10, 'Repositor'), (76, 11, 'Recepción médica'),
        (77, 13, 'Ayudante tambo'), (104, 22, 'Engrasador'), (121, 22, 'Lubricador'), (122, 23, 'Lavado automotor'),
        (107, 24, 'Ayudante de plomería'), (109, 27, 'Cajero'), (143, 11, 'Odontólogo/a'), (144, 11, 'Asistente Odontológico'),
        (165, 11, 'Psicólogo/a'), (171, 11, 'Chofer de Ambulancia'), (25, 9, 'Administrativo'), (11, 11, 'Médico'),
        (14, 26, 'Atención al cliente'), (19, 23, 'Mecánico'), (35, 24, 'Plomero'), (42, 29, 'Auxiliar de educación'),
        (44, 12, 'Soporte técnico'), (36, 22, 'Mantenimiento general'), (37, 8, 'Jardinero'), (62, 2, 'Operario de limpieza industrial'),
        (64, 2, 'Auxiliar de producción'), (83, 4, 'Ayudante de carpintería'), (66, 4, 'Ayudante de herrería'), (68, 5, 'Ayudante electricista industrial'),
        (86, 5, 'Cableador'), (87, 5, 'Canalizador'), (88, 6, 'Peón de obra'), (70, 8, 'Podador'), (72, 8, 'Mantenimiento de espacios verdes')
    ]

    for p_id, r_id, desc in puestos:
        try:
            rubro_obj = RubroEmpleo.objects.get(id_rubro=r_id)
            PuestoEmpleo.objects.get_or_create(id_puesto=p_id, defaults={'rubro': rubro_obj, 'descripcion': desc, 'activo': 'S'})
        except RubroEmpleo.DoesNotExist:
            pass

def reverse_load(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0011_alter_postulante_options_postulante_cv_and_more'),
    ]

    operations = [
        migrations.RunPython(load_data, reverse_load),
    ]
