# Generated by Django 6.0.3 on 2026-03-23 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0012_preload_puestos_rubros'),
        ('portal', '0002_localidad_vecino_localidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.localidad', verbose_name='Localidad'),
        ),
    ]
