# Generated by Django 6.0.3 on 2026-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0013_alter_postulante_localidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulante',
            old_name='domicilio',
            new_name='calle',
        ),
        migrations.AddField(
            model_name='postulante',
            name='altura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
