# Generated by Django 6.0.3 on 2026-03-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0014_rename_domicilio_postulante_calle_postulante_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=30, null=True),
        ),
    ]
