# Generated by Django 6.0.3 on 2026-03-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleo', '0015_alter_postulante_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='disponibilidad_viajar',
            field=models.CharField(blank=True, choices=[('S', 'Sí'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='licencia_conducir',
            field=models.CharField(blank=True, choices=[('S', 'Sí'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='movilidad_propia',
            field=models.CharField(blank=True, choices=[('S', 'Sí'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='situacion_actual',
            field=models.CharField(blank=True, choices=[('1', 'Desocupado'), ('2', 'Estudiante'), ('3', 'Trabajo Informal / Eventual'), ('4', 'Monotributista'), ('21', 'Empleado')], max_length=50, null=True),
        ),
    ]
