# Generated by Django 6.0.3 on 2026-03-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apicultor',
            fields=[
                ('id_apicultor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad')),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio')),
                ('cuit_cuil', models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIT/CUIL')),
                ('estado', models.CharField(default='Activo', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Observaciones')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Alta')),
            ],
            options={
                'verbose_name': 'Apicultor',
                'verbose_name_plural': 'Apicultores',
            },
        ),
        migrations.CreateModel(
            name='ApicultorCapacitacion',
            fields=[
                ('id_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_capacitacion', models.CharField(max_length=200, verbose_name='Nombre de Capacitación')),
                ('anio_cursado', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de Cursado')),
                ('titulo_imagen', models.ImageField(blank=True, null=True, upload_to='apicultura/capacitaciones/', verbose_name='Imagen del Título')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('apicultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='apicultura.apicultor')),
            ],
        ),
        migrations.CreateModel(
            name='ApicultorInstitucional',
            fields=[
                ('id_institucional', models.AutoField(primary_key=True, serialize=False)),
                ('pertenece_asociacion', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1)),
                ('usa_sala_extraccion', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='S', max_length=1)),
                ('extraccion_alter', models.CharField(blank=True, max_length=500, null=True, verbose_name='Extracción Alternativa')),
                ('apicultor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_institucionales', to='apicultura.apicultor')),
            ],
        ),
        migrations.CreateModel(
            name='ApicultorProductivo',
            fields=[
                ('id_productivo', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_colmenas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de Colmenas')),
                ('ubicacion_apiario', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ubicación Apiario')),
                ('nro_renapa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro RENAPA')),
                ('nro_rupp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nro RUPP')),
                ('apicultor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_productivos', to='apicultura.apicultor')),
            ],
        ),
        migrations.CreateModel(
            name='Extraccion',
            fields=[
                ('id_extraccion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_extraccion', models.DateField(verbose_name='Fecha de Extracción')),
                ('temporada', models.CharField(blank=True, max_length=20, null=True, verbose_name='Temporada')),
                ('tipo_miel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Miel')),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (Kg)')),
                ('precio_por_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Kg')),
                ('forma_pago', models.CharField(choices=[('ESPECIE', 'Especie'), ('DINERO', 'Dinero')], max_length=10, verbose_name='Forma de Pago')),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('id_operador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Operador')),
                ('apicultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracciones', to='apicultura.apicultor')),
            ],
            options={
                'verbose_name': 'Extracción',
                'verbose_name_plural': 'Extracciones',
                'ordering': ['-fecha_extraccion'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionExtraccion',
            fields=[
                ('id_liquidacion', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_total', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje Total')),
                ('kg_9_porciento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kg Retenidos (9%)')),
                ('importe_9_porciento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe Retenido (9%)')),
                ('forma_pago', models.CharField(choices=[('ESPECIE', 'Especie'), ('DINERO', 'Dinero')], max_length=10, verbose_name='Forma de Pago')),
                ('tipo_concepto', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Concepto')),
                ('sub_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sub Porcentaje')),
                ('extraccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacion', to='apicultura.extraccion')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
            },
        ),
    ]
