# Generated by Django 6.0.3 on 2026-03-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicultura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacionextraccion',
            name='extraccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='apicultura.extraccion'),
        ),
    ]
