# Generated by Django 6.0.3 on 2026-03-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicultura', '0003_alter_apicultor_localidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicultorcapacitacion',
            options={'verbose_name': 'Capacitación', 'verbose_name_plural': 'Capacitaciones'},
        ),
        migrations.AlterModelOptions(
            name='apicultorinstitucional',
            options={'verbose_name': 'Datos Institucionales', 'verbose_name_plural': 'Datos Institucionales'},
        ),
        migrations.AlterModelOptions(
            name='apicultorproductivo',
            options={'verbose_name': 'Datos de producción', 'verbose_name_plural': 'Datos de producción'},
        ),
        migrations.AddField(
            model_name='extraccion',
            name='nro_consecutivo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nro. de Extracción'),
        ),
    ]
