# Generated by Django 6.0.3 on 2026-03-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicultura', '0004_alter_apicultorcapacitacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacionextraccion',
            name='importe_9_porciento',
        ),
        migrations.RemoveField(
            model_name='liquidacionextraccion',
            name='kg_9_porciento',
        ),
        migrations.AddField(
            model_name='liquidacionextraccion',
            name='importe_retencion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Importe Retenido (10%)'),
        ),
        migrations.AddField(
            model_name='liquidacionextraccion',
            name='kg_retencion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kg Retenidos (10%)'),
        ),
        migrations.AlterField(
            model_name='apicultorinstitucional',
            name='pertenece_asociacion',
            field=models.CharField(blank=True, choices=[('S', 'Sí'), ('N', 'No')], max_length=1, null=True, verbose_name='Pertenece asociación'),
        ),
        migrations.AlterField(
            model_name='apicultorinstitucional',
            name='usa_sala_extraccion',
            field=models.CharField(blank=True, choices=[('S', 'Sí'), ('N', 'No')], max_length=1, null=True, verbose_name='Usa sala extracción'),
        ),
    ]
