# Generated by Django 6.0.3 on 2026-03-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicultura', '0005_remove_liquidacionextraccion_importe_9_porciento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicultor',
            name='domicilio',
        ),
        migrations.AddField(
            model_name='apicultor',
            name='altura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Altura/Nro'),
        ),
        migrations.AddField(
            model_name='apicultor',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='apicultor',
            name='calle',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Calle/Dirección'),
        ),
        migrations.AlterField(
            model_name='apicultor',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
