# Generated by Django 6.0.3 on 2026-03-20 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('domicilio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vecino_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vecino',
                'verbose_name_plural': 'Vecinos',
            },
        ),
    ]
