# Generated by Django 6.0.3 on 2026-03-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_localidad_vecino_localidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Enlace opcional')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='portal.vecino', verbose_name='Vecino')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
