# Generated by Django 6.0.3 on 2026-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_notificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vecino',
            old_name='domicilio',
            new_name='calle',
        ),
        migrations.AddField(
            model_name='vecino',
            name='altura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Altura'),
        ),
    ]
