"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6j((ys)amt4zbx+vv@osog04q$@yz6g$v-1w)m#=*6+@0_sj=6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'expedientes',
    'compras',
    'ferias',
    'apicultura',
    'empleo',
    'portal',
    'multas',
    'organigrama',
    'reclamos',
    'impuestos',
    'turnos',
    'capacitaciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'portal.middleware.SeparateAdminSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'reclamos.context_processors.unread_messages_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
import os
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'custom_static'),
]

JAZZMIN_SETTINGS = {
    "site_title": "Casilda Gestión",
    "site_header": "Municipalidad de Casilda",
    "site_brand": "Casilda Conecta",
    "site_logo": "img/logo_icon.png",
    "login_logo": "img/logo_muni.png",
    "welcome_sign": "Bienvenido al Sistema de Gestión Municipal",
        "hide_models": [
            "multas.Persona",
            "multas.Vehiculo",
            "multas.Inmueble",
            "multas.Animal",
            "multas.Inspector",
            "multas.Acta",
            "ferias.Subrubro",
            "empleo.Puesto",
            "organigrama.Area",
            "organigrama.Direccion",
            "organigrama.Departamento",
            "organigrama.Division",
            "organigrama.Subdivision",
            "organigrama.Seccion",
            "organigrama.Oficina",
            "capacitaciones.Capacitacion",
            "capacitaciones.Inscripcion",
            "expedientes.MovimientoExpediente",
            "apicultura.Apicultor",
            "apicultura.Extraccion",
            "apicultura.LiquidacionExtraccion"
        ],"show_ui_builder": False,
    "custom_css": "css/custom_admin.css?v=12",
    "custom_js": "js/admin_bell.js?v=12",
    "custom_links": {
        "impuestos": [
            {
                "name": "Gestión de Deuda",
                "url": "admin:impuestos_deuda_changelist",
                "icon": "fas fa-file-invoice-dollar",
            },
            {
                "name": "Carga Masiva",
                "url": "admin:impuestos_deuda_changelist",
                "icon": "fas fa-upload",
            }
        ],
        "turnos": [
            {
                "name": "Ver Turnos Solicitados",
                "url": "admin:turnos_turno_changelist",
                "icon": "fas fa-calendar-check",
            },
            {
                "name": "Generar Franjas (Config)",
                "url": "admin:turnos_configuracionturno_changelist",
                "icon": "fas fa-cogs",
            }
        ],
        "capacitaciones": [
            {
                "name": "Crear capacitacion",
                "url": "admin:capacitaciones_capacitacion_add",
                "icon": "fas fa-plus",
            },
            {
                "name": "Lista de Capacitaciones",
                "url": "admin:capacitaciones_capacitacion_changelist",
                "icon": "fas fa-chalkboard-teacher",
            },
            {
                "name": "Inscriptos",
                "url": "admin:capacitaciones_inscripcion_changelist",
                "icon": "fas fa-users",
            }
        ],
        "expedientes": [
            {
                "name": "Nuevo Expediente",
                "url": "admin:expedientes_expediente_add",
                "icon": "fas fa-file-alt",
            },
            {
                "name": "Responder (Dar Pase)",
                "url": "admin:expedientes_movimientoexpediente_add",
                "icon": "fas fa-share",
            },
            {
                "name": "Gestión de Expedientes",
                "url": "admin:expedientes_expediente_changelist",
                "icon": "fas fa-folder-open",
            }
        ],
        "multas": [
            {
                "name": "Carga Acta",
                "url": "admin:multas_acta_add",
                "icon": "fas fa-plus",
            },
            {
                "name": "Consulta y Edición",
                "url": "admin:multas_acta_changelist",
                "icon": "fas fa-edit",
            },
            {
                "name": "Inspectores",
                "url": "admin:multas_inspector_changelist",
                "icon": "fas fa-user-shield",
            },
            {
                "name": "Página del Vecino", 
                "url": "multas:index_consultas", 
                "icon": "fas fa-globe",
            }
        ],
        "organigrama": [
            {
                "name": "Nuevo Empleado",
                "url": "admin:organigrama_funcionario_add",
                "icon": "fas fa-user-plus",
            },
            {
                "name": "Nómina de Empleados",
                "url": "admin:organigrama_funcionario_changelist",
                "icon": "fas fa-users-cog",
            }
        ],
        "empleo": [{
            "name": "Nuevo postulante", 
            "url": "admin:empleo_postulante_add", 
            "icon": "fas fa-user-plus",
        },
        {
            "name": "Perfiles Laborales y CV", 
            "url": "empleo:perfiles_cv", 
            "icon": "fas fa-search",
        }],
        "ferias": [{
            "name": "Nuevo feriante", 
            "url": "admin:ferias_feriante_add", 
            "icon": "fas fa-user-plus",
        }],
        "apicultura": [
            {"name": "Nuevo apicultor", "url": "admin:apicultura_apicultor_add", "icon": "fas fa-user-plus"},
            {"name": "Listado de apicultores", "url": "admin:apicultura_apicultor_changelist", "icon": "fas fa-users"},
            {"name": "Nueva extracción", "url": "admin:apicultura_extraccion_add", "icon": "fas fa-plus-circle"},
            {"name": "Listado de extracciones", "url": "admin:apicultura_extraccion_changelist", "icon": "fas fa-clipboard-list"},
            {"name": "Generar informe", "url": "/admin/apicultura/generar-informe/", "icon": "fas fa-file-pdf"},
        ]
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "cosmo",
    "dark_mode_theme": None,
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-light",
    "accent": "accent-success",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_hover_elevate": False,
    "sidebar_activate_nav_attr": False,
    "resource_panel": True,
    "controls_sidebar": True,
    "show_ui_builder": False,
    "presets": [],
    "styles": {
        "success": "background-color: #14855e !important; border-color: #14855e !important;",
    }
}
