# Generated by Django 6.0.3 on 2026-03-23 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Detalles del curso, horarios, lugar, etc.')),
                ('area_responsable', models.CharField(choices=[('ASAC', 'Seguridad Alimentaria (ASAC)'), ('PRODUCCION', 'Producción y Oficios'), ('QUINQUELA', 'Cultura (Quinquela Martín)')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('cupo_maximo', models.IntegerField(help_text='Cantidad máxima de inscriptos permitidos. Cuando se alcanza, la inscripción se cierra automáticamente.')),
                ('estado_inscripcion', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=20)),
            ],
            options={
                'verbose_name': 'Capacitación / Taller',
                'verbose_name_plural': 'Capacitaciones y Talleres',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('CANCELADO', 'Cancelado por el Vecino o Autoridad'), ('FINALIZADO', 'Finalizó/Asistió')], default='INSCRIPTO', max_length=20)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='capacitaciones.capacitacion')),
                ('vecino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones', to='portal.vecino')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('capacitacion', 'vecino')},
            },
        ),
    ]
