# Generated by Django 6.0.3 on 2026-03-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='dias_dictado',
            field=models.CharField(blank=True, help_text='Ej: Lunes y Miércoles', max_length=100, null=True, verbose_name='Días de dictado'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='horarios',
            field=models.CharField(blank=True, help_text='Ej: 18:00 a 20:00 hs', max_length=100, null=True, verbose_name='Horarios'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar/Aula'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='area_responsable',
            field=models.CharField(choices=[('ASAC', 'Seguridad Alimentaria (ASAC)'), ('PRODUCCION', 'Área de Producción, Ciencia y Tecnología'), ('QUINQUELA', 'Cultura (Quinquela Martín)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='cupo_maximo',
            field=models.IntegerField(help_text='Cantidad máxima de inscriptos permitidos.'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
