# Generated by Django 6.0.3 on 2026-03-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacitaciones', '0002_capacitacion_dias_dictado_capacitacion_horarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='capacitaciones/certificados/', verbose_name='Certificado en PDF'),
        ),
    ]
