# Generated by Django 6.0.3 on 2026-03-22 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TGI', 'Tasa General de Inmuebles'), ('MUNICIPAL', 'Impuesto Municipal')], max_length=20)),
                ('vecino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='portal.vecino')),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
            },
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Ej: Enero 2026', max_length=20)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='impuestos.impuesto')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='PartidaInmobiliaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclatura', models.CharField(max_length=50, unique=True, verbose_name='Nomenclatura Catastral')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('vecino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='portal.vecino')),
            ],
            options={
                'verbose_name': 'Partida Inmobiliaria',
                'verbose_name_plural': 'Partidas Inmobiliarias',
            },
        ),
        migrations.AddField(
            model_name='impuesto',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='impuestos.partidainmobiliaria'),
        ),
    ]
